name: onepool
services:

  postgres-app:
    image: postgres:14.2-alpine
    container_name: onepool-postgres-app
    ports:
      - "24900:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./psql-data/app:/var/lib/postgresql/onepool/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: OnePool
      PGDATA: /var/lib/postgresql/onepool/data/pgdata
    restart: unless-stopped

  backend:
    image: zelytra/onepool-backend:latest
    container_name: onepool-backend
    depends_on:
      - keycloak
      - postgres-app
    ports:
      - "24901:8080"
    environment:
      DB_HOST: postgres-app
      DB_DATABASE: OnePool
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_HOST: ${PUBLIC_KEYCLOAK_HOSTNAME}
    restart: unless-stopped

  frontend:
    image: zelytra/onepool-webapp:latest
    container_name: onepool-website
    depends_on:
      - keycloak
      - postgres-app
      - backend
    ports:
      - "24902:80"
    environment:
      VITE_BACKEND_HOST: ${PUBLIC_QUARKUS_HOSTNAME}
      VITE_KEYCLOAK_HOST: ${PUBLIC_KEYCLOAK_HOSTNAME}
    restart: unless-stopped

  postgres-auth:
    image: postgres:14.2-alpine
    container_name: onepool-postgres-auth
    ports:
      - "24903:5432"
    volumes:
      - ./psql-data/auth:/var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: Keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: onepool-keycloak
    depends_on:
      - postgres-auth
    ports:
      - "24904:8080"
    volumes:
      - ./keycloak/config:/opt/keycloak/data/import
      - ./keycloak/themes/onepool:/opt/keycloak/themes/onepool
      - /etc/localtime:/etc/localtime:ro
    command: start --import-realm
    environment:
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-auth
      PROXY_ADDRESS_FORWARDING: "true"
      KC_PROXY: edge
      KC_DB_URL_DATABASE: Keycloak
      KC_VAULT_FILE: /var/keycloak/vault
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_OVERRIDE: "false"
    restart: unless-stopped