name: "CI"

on:
  pull_request: # Triggered on pull requests to any branch
  push:
    branches: # Additionally, trigger on push events to specific branches
      - master

jobs:
  backend-build:
    runs-on: ubuntu-latest
    name: Quarkus build test
    defaults:
      run:
        working-directory: 'backend'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn quarkus:build package

  backend-test:
    name: Quarkus UT
    defaults:
      run:
        working-directory: 'backend'
    runs-on: ubuntu-latest
    # Permissions block is optional, useful for dependabot checks
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

  webapp-build:
    name: Webapp Vite build test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    defaults:
      run:
        working-directory: 'webapp'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json
      - run: npm ci
      - run: npm run build --if-present